services:

  wordpress:
    container_name: ${PROJECT_NAME}_wp
    image: wordpress:latest
    restart: unless-stopped
    ports:
      - ${PROJECT_PORT}:80
    environment:
      WORDPRESS_DB_HOST: ${PROJECT_NAME}_db
      WORDPRESS_DB_USER: ${PROJECT_DB_USER}
      WORDPRESS_DB_PASSWORD: ${PROJECT_DB_PASSWORD}
      WORDPRESS_DB_NAME: ${PROJECT_DB_NAME}
      WORDPRESS_TABLE_PREFIX: ${PROJECT_TABLE_PREFIX}
      WORDPRESS_DEBUG: ${PROJECT_DEBUG}
    volumes:
      - ./wp-content:/var/www/html/wp-content
    depends_on:
      - db

  db:
    container_name: ${PROJECT_NAME}_db
    image: mysql:5.7
    restart: unless-stopped
    environment:
      MYSQL_DATABASE: ${PROJECT_DB_NAME}
      MYSQL_USER: ${PROJECT_DB_USER}
      MYSQL_PASSWORD: ${PROJECT_DB_PASSWORD}
      MYSQL_RANDOM_ROOT_PASSWORD: '1'
    volumes:
      - ./db-volume:/var/lib/mysql
